name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Build assets
      run: npm install && npm run build

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Decode .env
      run: |
        echo "${{ secrets.ENV_BASE64 }}" | base64 --decode > .env

    - name: Prepare deploy.zip
      run: |
        mkdir build
        rsync -a --exclude=node_modules --exclude=.git --exclude=tests --exclude=storage/logs --exclude=vendor ./ build/
        cp -r vendor build/
        cp -r storage build/
        cp -r bootstrap build/
        cp -r public build/
        cp .env build/

        # Buat ZIP dari folder build/
        cd build
        zip -r ../deploy.zip . -x "node_modules/*" ".git/*"
        cd ..

    - name: Upload deploy.zip via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        exclude: |
          *
        include: |
          deploy.zip
